### ISSUE TITLE
Refactor AI into state machine

### ISSUE THREAD

**Issue by jdpdev** [dupersaurus/sandlot-basenoball#14]
Refactor base runner and fielder AI routines into a state machine. 

**Runners**
- [ ] #15 Force out
- [ ] #16 Free running (no force)
- [ ] #17 Tagging up to run
- [ ] #18 Tagging up to retreat

**Fielders**
- [ ] #19 Running to gather ball
- [ ] #20 Run to cover base
