### ISSUE TITLE
Refactor gameplay into encounters

### ISSUE THREAD

**Issue by jdpdev** [dupersaurus/sandlot-basenoball#9]
### Encounters

When two players face off against each other (pitcher/batter, fielder/runner, etc), it is called an **encounter**.

Each encounter: 
- Contains logic and calculations about how to resolve the encounter
- Opens a UI (perhaps specific to the encounter) to show the player what is happening

When the game detects an encounter happening, it begins an encounter of the specific type to handle the action.
#### Basic Encounters
- [ ] #10 Batting/pitching
- [ ] #11 Fielding the ball, gathering (after a hit)
- [ ] #12 Base-fielder vs runner, force out
- [ ] #13 Base-fielder vs runner, no force out
